# Generated by Django 2.2.28 on 2022-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('noOfVisits', models.IntegerField()),
                ('noOfLikes', models.IntegerField()),
                ('car', models.CharField(choices=[('Kia', 'Kia'), ('BMW', 'BMW'), ('Hyundai', 'Hyundai'), ('Audi', 'Audi'), ('Ferrari', 'Ferrari'), ('Mercedes', 'Mercedes')], max_length=100)),
            ],
        ),
    ]
