# Generated by Django 2.2.28 on 2022-04-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='noOfLikes',
            new_name='numberOfLikes',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='noOfVisits',
            new_name='numberOfVisits',
        ),
        migrations.RemoveField(
            model_name='category',
            name='car',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
