# Generated by Django 2.2.28 on 2022-04-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220429_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='car',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=2, max_length=100),
            preserve_default=False,
        ),
    ]
